before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare
git:
  strategy: tarball
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - ruby-head
bundler_args: --jobs=3 --retry=3 --deployment --local --without development
matrix:
  allow_failures:
    - rvm: 2.1
    - rvm: ruby-head
services:
  - redis-server
